services:
  - type: web
    name: taxrating-backend
    env: python
    plan: free
    buildCommand: "pip install -r backend/requirements.txt"
    startCommand: "uvicorn app.main:app --host 0.0.0.0 --port 10000"
    workingDir: backend
    envVars:
      - key: MONGODB_URL
        value: "mongodb+srv://admin:admin123@clusterehv.rxzuuxp.mongodb.net/?retryWrites=true&w=majority&appName=ClusterEHV"
